# Generated by Django 4.2.11 on 2025-07-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0030_altertblProfessions'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS public."tblHandicap_Non";',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS public."tblMaladieinvalidante_Non";',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS public."tblCouvertureAssuranceMutuelle";',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS public."tblTypesHabitation";',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.CreateModel(
            name='CouvertureAssuranceMutuelle',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('CouvertureAssuranceMutuelle', models.CharField(blank=True, db_column='CouvertureAssuranceMutuelle', max_length=150, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=150, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblCouvertureAssuranceMutuelle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Handicap_Non',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('HandicapNon', models.CharField(blank=True, db_column='HandicapNon', max_length=100, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=100, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblHandicap_Non',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Maladieinvalidante_Non',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('MaladieInvalidanteNon', models.CharField(blank=True, db_column='MaladieInvalidanteNon', max_length=100, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=100, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblMaladieinvalidante_Non',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Milieuderesidence',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('Milieuderesidence', models.CharField(blank=True, db_column='MilieuDeResidence', max_length=100, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=100, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblMilieuderesidence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypesHabitation',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('TypesHabitation', models.CharField(blank=True, db_column='TypesDhabitation', max_length=150, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=150, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblTypesHabitation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='insuree',
            name='couverture_assurance_mutuelle',
            field=models.ForeignKey(blank=True, db_column='CouvertureAssuranceMutuelle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.couvertureassurancemutuelle'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='handicap_non',
            field=models.ForeignKey(blank=True, db_column='HandicapNon', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.handicap_non'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='maladie_invalidante_non',
            field=models.ForeignKey(blank=True, db_column='MaladieInvalidante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.maladieinvalidante_non'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='milieu_de_residence',
            field=models.ForeignKey(blank=True, db_column='MilieuDeResidence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.milieuderesidence'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='types_habitation',
            field=models.ForeignKey(blank=True, db_column='TypesHabitation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.typeshabitation'),
        ),
    ]
